services:
  - type: web
    name: frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: frontend/tracking-notas/public
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn TrackingNotas.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TrackingNotas.settings
