# Generated by Django 5.0.6 on 2024-07-28 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre'),
        ),
    ]
