# Generated by Django 5.0.6 on 2024-07-28 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitreport',
            name='idStudent',
        ),
        migrations.AddField(
            model_name='unitreport',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
