# Generated by Django 5.0.6 on 2024-07-28 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_unitreport_idstudent_unitreport_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegradesstudent',
            name='idStudent',
        ),
        migrations.AddField(
            model_name='coursegradesstudent',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
