# Generated by Django 5.0.6 on 2024-07-28 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_coursegradesstudent_idstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegradesstudent',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
